services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.6.10
    container_name: open-webui
    volumes:
      - ${VOLUMES_DIR}/open-webui/data:/app/backend/data
    environment:
      DEFAULT_USER_ROLE: user
      JWT_EXPIRES_IN: 1d
      ENABLE_LOGIN_FORM: false
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_ROLES_CLAIM: ${OAUTH_ROLES_CLAIM}
      OAUTH_ALLOWED_ROLES: ${OAUTH_ALLOWED_ROLES}
      OAUTH_ADMIN_ROLES: ${OAUTH_ADMIN_ROLES}
      OPENID_PROVIDER_URL: ${OPENID_PROVIDER_URL}
      OAUTH_PROVIDER_NAME: ${OAUTH_PROVIDER_NAME}
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.open-webui.rule: Host(`chat.ryanmalonzo.com`)
      traefik.http.routers.open-webui.entrypoints: websecure
      traefik.http.routers.open-webui.tls.certresolver: cloudflare
      traefik.http.services.open-webui.loadbalancer.server.port: 8080
      # glance
      glance.name: Open WebUI
      glance.icon: sh:open-webui
      glance.url: https://chat.ryanmalonzo.com/

networks:
  proxy:
    external: true
