services:
  web:
    image: ghcr.io/hoarder-app/hoarder:0.22.0
    volumes:
      - ${VOLUMES_DIR}/hoarder/data:/data
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env
    networks:
      - hoarder
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.hoarder.rule: Host(`hoarder.ryanmalonzo.com`)
      traefik.http.routers.hoarder.entrypoints: websecure
      traefik.http.routers.hoarder.tls.certresolver: cloudflare
      traefik.http.services.hoarder.loadbalancer.server.port: 3000
      # glance
      glance.name: hoarder
      glance.icon: sh:hoarder
      glance.url: https://hoarder.ryanmalonzo.com/

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    environment:
      MEILI_NO_ANALYTICS: true
    env_file:
      - .env
    volumes:
      - meilisearch:/meili_data
    networks:
      - hoarder
    restart: unless-stopped

volumes:
  meilisearch:

networks:
  hoarder:
    name: hoarder
  proxy:
    external: true
