apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: navidrome
          image: ghcr.io/navidrome/navidrome:0.63.2
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
              readOnly: true
          env:
            - name: ND_BASEURL
              value: "https://navidrome.internal.chaldea.dev"
            - name: ND_ENABLEINSIGHTSCOLLECTOR
              value: "false"
            - name: ND_ENFORCENONROOTUSER
              value: "true"
            - name: ND_DEFAULTTHEME
              value: "Spotify-ish"
            - name: ND_LOGLEVEL
              value: "info"
            - name: TZ
              value: "Europe/Paris"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-config
        - name: music
          persistentVolumeClaim:
            claimName: navidrome-music
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
