apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-config
  labels:
    name: navidrome-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/navidrome/config"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music
  labels:
    name: navidrome-music
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tank/music"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
