apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: navidrome-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: navidrome-music
