---
- name: Install cron
  ansible.builtin.apt:
    name: cron
    state: present

- name: Schedule docker system prune
  ansible.builtin.cron:
    name: "Docker system prune"
    minute: "{{ docker_cron_prune_minute }}"
    hour: "{{ docker_cron_prune_hour }}"
    day: "{{ docker_cron_prune_day }}"
    weekday: "{{ docker_cron_prune_weekday }}"
    month: "{{ docker_cron_prune_month }}"
    job: "/usr/bin/docker system prune -af --filter 'until={{ docker_cron_prune_until }}' > /var/log/docker-prune.log 2>&1"
