name: bentopdf

services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:v1.5.1
    container_name: bentopdf
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    labels:
      pangolin.proxy-resources.bentopdf.name: BentoPDF
      pangolin.proxy-resources.bentopdf.protocol: http
      pangolin.proxy-resources.bentopdf.full-domain: pdf.ryanmalonzo.com
      pangolin.proxy-resources.bentopdf.auth.sso-enabled: true
      pangolin.proxy-resources.bentopdf.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.bentopdf.targets[0].port: 8080
      pangolin.proxy-resources.bentopdf.targets[0].method: http
    restart: unless-stopped
