apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  labels:
    name: downloads
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/downloads"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
