apiVersion: v1
kind: PersistentVolume
metadata:
  name: profilarr-config
  labels:
    name: profilarr-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/profilarr/config"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
