services:
  tailscale-vaultwarden:
    image: tailscale/tailscale:v1.82
    container_name: tailscale-vaultwarden
    hostname: vaultwarden
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}?ephemeral=false
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/vaultwarden.json
    volumes:
      - ${VOLUMES_DIR}/vaultwarden/tailscale:/config
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    labels:
      glance.parent: vaultwarden
      glance.name: Tailscale

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ${VOLUMES_DIR}/vaultwarden/data:/data
    environment:
      DOMAIN: https://vaultwarden.owl-augmented.ts.net
    depends_on:
      - tailscale-vaultwarden
    network_mode: service:tailscale-vaultwarden
    restart: unless-stopped
    labels:
      glance.id: vaultwarden
      glance.name: Vaultwarden
      glance.icon: sh:vaultwarden
      glance.url: https://vaultwarden.owl-augmented.ts.net/

volumes:
  tailscale:
