name: jellyfin

x-common-variables: &common-variables
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1001}
  TZ: ${TZ}

x-restart-policy: &restart-policy
  restart: unless-stopped

x-linuxserver-base: &linuxserver-base
  <<: *restart-policy
  environment:
    <<: *common-variables

x-radarr-base: &radarr-base
  <<: *linuxserver-base
  image: lscr.io/linuxserver/radarr:5.27.5

x-sonarr-base: &sonarr-base
  <<: *linuxserver-base
  image: lscr.io/linuxserver/sonarr:4.0.15

x-profilarr-base: &profilarr-base
  <<: *restart-policy
  image: santiagosayshey/profilarr:v1.1.3
  environment:
    TZ: ${TZ}

services:
  jellyfin:
    <<: *restart-policy
    image: ghcr.io/jellyfin/jellyfin:10.11.0-rc6
    container_name: jellyfin
    user: ${PUID}:${PGID}
    ports:
      - "7359:7359/udp"
      - "8096:8096"
    volumes:
      - jellyfin-cache:/cache
      - jellyfin-config:/config
      - ${NFS_MEDIA}/anime/tv:/data/anime/tv
      - ${NFS_MEDIA}/anime/movies:/data/anime/movies
      - ${NFS_MEDIA}/non-anime/tv:/data/non-anime/tv
      - ${NFS_MEDIA}/non-anime/movies:/data/non-anime/movies
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.ryanmalonzo.com
    labels:
      pangolin.proxy-resources.jellyfin.name: Jellyfin
      pangolin.proxy-resources.jellyfin.protocol: http
      pangolin.proxy-resources.jellyfin.full-domain: jellyfin.ryanmalonzo.com
      pangolin.proxy-resources.jellyfin.auth.sso-enabled: false
      pangolin.proxy-resources.jellyfin.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.jellyfin.targets[0].port: 8096
      pangolin.proxy-resources.jellyfin.targets[0].method: http

  jellyseerr:
    <<: *restart-policy
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    ports:
      - "5055:5055"
    volumes:
      - jellyseerr:/app/config
    environment:
      LOG_LEVEL: debug
      PORT: 5055
      TZ: ${TZ}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      pangolin.proxy-resources.jellyseerr.name: Jellyseerr
      pangolin.proxy-resources.jellyseerr.protocol: http
      pangolin.proxy-resources.jellyseerr.full-domain: jellyseerr.ryanmalonzo.com
      pangolin.proxy-resources.jellyseerr.auth.sso-enabled: false
      pangolin.proxy-resources.jellyseerr.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.jellyseerr.targets[0].method: http

  prowlarr:
    <<: *linuxserver-base
    image: lscr.io/linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - prowlarr:/config
    labels:
      pangolin.proxy-resources.prowlarr.name: Prowlarr
      pangolin.proxy-resources.prowlarr.protocol: http
      pangolin.proxy-resources.prowlarr.full-domain: prowlarr.ryanmalonzo.com
      pangolin.proxy-resources.prowlarr.auth.sso-enabled: true
      pangolin.proxy-resources.prowlarr.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.prowlarr.targets[0].method: http

  sabnzbd:
    <<: *linuxserver-base
    image: lscr.io/linuxserver/sabnzbd:4.5.3
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - sabnzbd:/config
      - ${INCOMPLETE_DOWNLOADS_DIR}:/incomplete-downloads
      - ${DOWNLOADS_DIR}:/downloads
    labels:
      pangolin.proxy-resources.sabnzbd.name: SABnzbd
      pangolin.proxy-resources.sabnzbd.protocol: http
      pangolin.proxy-resources.sabnzbd.full-domain: sabnzbd.ryanmalonzo.com
      pangolin.proxy-resources.sabnzbd.auth.sso-enabled: true
      pangolin.proxy-resources.sabnzbd.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.sabnzbd.targets[0].method: http

  radarr:
    <<: *radarr-base
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - radarr:/config
      - ${NFS_MEDIA}/anime/movies:/movies
      - ${DOWNLOADS_DIR}:/downloads
    labels:
      pangolin.proxy-resources.radarr.name: Radarr
      pangolin.proxy-resources.radarr.protocol: http
      pangolin.proxy-resources.radarr.full-domain: radarr.ryanmalonzo.com
      pangolin.proxy-resources.radarr.auth.sso-enabled: true
      pangolin.proxy-resources.radarr.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.radarr.targets[0].method: http

  sonarr:
    <<: *sonarr-base
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - sonarr:/config
      - ${NFS_MEDIA}/anime/tv:/tv
      - ${DOWNLOADS_DIR}:/downloads
    labels:
      pangolin.proxy-resources.sonarr.name: Sonarr
      pangolin.proxy-resources.sonarr.protocol: http
      pangolin.proxy-resources.sonarr.full-domain: sonarr.ryanmalonzo.com
      pangolin.proxy-resources.sonarr.auth.sso-enabled: true
      pangolin.proxy-resources.sonarr.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.sonarr.targets[0].method: http

  profilarr:
    <<: *profilarr-base
    container_name: profilarr
    ports:
      - "6868:6868"
    volumes:
      - profilarr:/config
    labels:
      pangolin.proxy-resources.profilarr.name: Profilarr
      pangolin.proxy-resources.profilarr.protocol: http
      pangolin.proxy-resources.profilarr.full-domain: profilarr.ryanmalonzo.com
      pangolin.proxy-resources.profilarr.auth.sso-enabled: true
      pangolin.proxy-resources.profilarr.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.profilarr.targets[0].method: http

  radarr-nonanime:
    <<: *radarr-base
    container_name: radarr-nonanime
    ports:
      - "7879:7878"
    volumes:
      - radarr-nonanime:/config
      - ${NFS_MEDIA}/non-anime/movies:/movies
      - ${DOWNLOADS_DIR}:/downloads
    labels:
      pangolin.proxy-resources.radarr-nonanime.name: Radarr (Others)
      pangolin.proxy-resources.radarr-nonanime.protocol: http
      pangolin.proxy-resources.radarr-nonanime.full-domain: radarr-nonanime.ryanmalonzo.com
      pangolin.proxy-resources.radarr-nonanime.auth.sso-enabled: true
      pangolin.proxy-resources.radarr-nonanime.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.radarr-nonanime.targets[0].port: 7879
      pangolin.proxy-resources.radarr-nonanime.targets[0].method: http

  sonarr-nonanime:
    <<: *sonarr-base
    container_name: sonarr-nonanime
    ports:
      - "8990:8989"
    volumes:
      - sonarr-nonanime:/config
      - ${NFS_MEDIA}/non-anime/tv:/tv
      - ${DOWNLOADS_DIR}:/downloads
    labels:
      pangolin.proxy-resources.sonarr-nonanime.name: Sonarr (Others)
      pangolin.proxy-resources.sonarr-nonanime.protocol: http
      pangolin.proxy-resources.sonarr-nonanime.full-domain: sonarr-nonanime.ryanmalonzo.com
      pangolin.proxy-resources.sonarr-nonanime.auth.sso-enabled: true
      pangolin.proxy-resources.sonarr-nonanime.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.sonarr-nonanime.targets[0].port: 8990
      pangolin.proxy-resources.sonarr-nonanime.targets[0].method: http

  profilarr-nonanime:
    <<: *profilarr-base
    container_name: profilarr-nonanime
    ports:
      - "6869:6868"
    volumes:
      - profilarr-nonanime:/config
    labels:
      pangolin.proxy-resources.profilarr-nonanime.name: Profilarr (Others)
      pangolin.proxy-resources.profilarr-nonanime.protocol: http
      pangolin.proxy-resources.profilarr-nonanime.full-domain: profilarr-nonanime.ryanmalonzo.com
      pangolin.proxy-resources.profilarr-nonanime.auth.sso-enabled: true
      pangolin.proxy-resources.profilarr-nonanime.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.profilarr-nonanime.targets[0].port: 6869
      pangolin.proxy-resources.profilarr-nonanime.targets[0].method: http

volumes:
  jellyfin-cache:
  jellyfin-config:
  jellyseerr:
  profilarr:
  profilarr-nonanime:
  prowlarr:
  qbittorrent:
  radarr:
  radarr-nonanime:
  sabnzbd:
  sonarr:
  sonarr-nonanime:
