name: jellyfin

x-common-variables: &common-variables
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1001}
  TZ: ${TZ}

x-restart-policy: &restart-policy
  restart: unless-stopped

x-linuxserver-base: &linuxserver-base
  <<: *restart-policy
  environment:
    <<: *common-variables

x-radarr-base: &radarr-base
  <<: *linuxserver-base
  image: lscr.io/linuxserver/radarr:5.27.5

x-sonarr-base: &sonarr-base
  <<: *linuxserver-base
  image: lscr.io/linuxserver/sonarr:4.0.15

x-profilarr-base: &profilarr-base
  <<: *restart-policy
  image: santiagosayshey/profilarr:v1.1.3
  environment:
    TZ: ${TZ}

services:
  jellyfin:
    <<: *restart-policy
    image: ghcr.io/jellyfin/jellyfin:10.11.0-rc6
    container_name: jellyfin
    user: 1000:1001
    ports:
      - "7359:7359/udp"
      - "8096:8096"
    volumes:
      - jellyfin-cache:/cache
      - jellyfin-config:/config
      - ${NFS_MEDIA}/anime/tv:/data/anime/tv
      - ${NFS_MEDIA}/anime/movies:/data/anime/movies
      - ${NFS_MEDIA}/non-anime/tv:/data/non-anime/tv
      - ${NFS_MEDIA}/non-anime/movies:/data/non-anime/movies
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.ryanmalonzo.com

  jellyseerr:
    <<: *restart-policy
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    ports:
      - "5055:5055"
    volumes:
      - jellyseerr:/app/config
    environment:
      LOG_LEVEL: debug
      PORT: 5055
      TZ: ${TZ}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3

  prowlarr:
    <<: *linuxserver-base
    image: lscr.io/linuxserver/prowlarr:2.0.5
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - prowlarr:/config

  sabnzbd:
    <<: *linuxserver-base
    image: lscr.io/linuxserver/sabnzbd:4.5.3
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - sabnzbd:/config
      - ${INCOMPLETE_DOWNLOADS_DIR}:/incomplete-downloads
      - ${DOWNLOADS_DIR}:/downloads

  qbittorrent:
    <<: *linuxserver-base
    image: lscr.io/linuxserver/qbittorrent:5.1.2
    container_name: qbittorrent
    ports:
      - "8081:8081"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      <<: *common-variables
      WEBUI_PORT: 8081
      TORRENTING_PORT: 6881

  radarr:
    <<: *radarr-base
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - radarr:/config
      - ${NFS_MEDIA}/anime/movies:/movies
      - ${DOWNLOADS_DIR}:/downloads

  sonarr:
    <<: *sonarr-base
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - sonarr:/config
      - ${NFS_MEDIA}/anime/tv:/tv
      - ${DOWNLOADS_DIR}:/downloads

  profilarr:
    <<: *profilarr-base
    container_name: profilarr
    ports:
      - "6868:6868"
    volumes:
      - profilarr:/config

  radarr-nonanime:
    <<: *radarr-base
    container_name: radarr-nonanime
    ports:
      - "7879:7878"
    volumes:
      - radarr-nonanime:/config
      - ${NFS_MEDIA}/non-anime/movies:/movies
      - ${DOWNLOADS_DIR}:/downloads

  sonarr-nonanime:
    <<: *sonarr-base
    container_name: sonarr-nonanime
    ports:
      - "8990:8989"
    volumes:
      - sonarr-nonanime:/config
      - ${NFS_MEDIA}/non-anime/tv:/tv
      - ${DOWNLOADS_DIR}:/downloads

  profilarr-nonanime:
    <<: *profilarr-base
    container_name: profilarr-nonanime
    ports:
      - "6869:6868"
    volumes:
      - profilarr-nonanime:/config

volumes:
  jellyfin-cache:
  jellyfin-config:
  jellyseerr:
  profilarr:
  profilarr-nonanime:
  prowlarr:
  qbittorrent:
  radarr:
  radarr-nonanime:
  sabnzbd:
  sonarr:
  sonarr-nonanime:
