name: jellyfin

services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.0-rc5
    container_name: jellyfin
    user: 1000:1001
    ports:
      - "7359:7359/udp"
      - "8096:8096"
    volumes:
      - jellyfin-cache:/cache
      - jellyfin-config:/config
      - ${NFS_MEDIA}/anime/tv:/data/anime/tv
      - ${NFS_MEDIA}/anime/movies:/data/anime/movies
      - ${NFS_MEDIA}/non-anime/tv:/data/non-anime/tv
      - ${NFS_MEDIA}/non-anime/movies:/data/non-anime/movies
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.ryanmalonzo.com
    restart: "unless-stopped"

volumes:
  jellyfin-cache:
  jellyfin-config:
