all:
  children:
    proxmox:
      hosts:
        proxmox-host:
          ansible_host: 192.168.1.35
          ansible_user: root
          ansible_ssh_private_key_file: /Users/ryanmalonzo/.ssh/chaldea
          ansible_ssh_common_args: "-o IdentitiesOnly=yes"
    docker:
      hosts:
        docker-vm:
          ansible_host: 192.168.1.251
          ansible_user: chaldea
          ansible_ssh_private_key_file: /Users/ryanmalonzo/.ssh/chaldea
          ansible_ssh_common_args: "-o IdentitiesOnly=yes"
