---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    cloudflared: AgAvE4jwtdBFdSDMFUOOtRlYirSckj+/e2Teu0dfT1FaF4jhNcnetk6OIwHFuMJvAImB/GDVOjmRB/MJMB0l4Ag78WCqNRtZqKPf8ljsEqXOkWc+NysE4LDK5WV8ubb8sR0vMpU5d7kF3RgAK5cVrPkJB+J1MH48t5wN0MGSOGysPQeh+znwn6TQLQc/Yp3V9r9jIbrEVv2OY9nEvxfbD1KUQDLkhJqMoZbgxpno0SHCkgWsdPnuNpaBXZ/FuElqjyijT4Ra90KBN+FFGchb2N/cbYIDNSpn0a1aOJs6RGfpNTO79WlM/S9ZU1/+HbpZyDf2SK4rLlInC4wrRwQkH3IDAvwZXS/8IdMxGvNzodp7OJlr7wlVbXxnPk8o7Ud2Ib3FCtAC4rmO9lz7K8NPwjlCV+9UswpuRcrf4oPB9XkKqNfqsiby/OdkD1MwvQjVUcmiTK4a3z4j3+ayu0aLEvcZobrKb3SKOjjAs7rcRnFifseD7S0UV7R4HDvvE8qyhnFf5zumZQz6k78v22Bhy0kOORO9SHcodWrDj/+fZPueHQFNl1x5B6PSzNB2UzPM//E/szhyvDzo67T4b/LNk+DwlGLRQd088YNU8roFDzhlSPjGmCYceIIlvTuK003dfIq3CxypgdPysmirIQwIpd+MJvZ8giOUNWPpG6m/m1BIw6wiODGPIYoH+tCyHeeU/AITdIy1pwxJLQyAgyq6qEnKT0r4uLSS6qsB6Zg5l59LmjRTjkuYOl6HJA8Do7Qec5K7R1C6NRTuppGkYB9e0odpyvlW5DzoaLfLk9kQy1kmma2FlgaLy1Ky8jxd0m0MKKaubeD4GP461GjkTdO1vFRyuo1nRS1mhjiwpfe3A1X0lrYdjBpoBmwK8I/gF/f2nISL5xNBOuS6oOqETc5bmGL4OyBoETR4Hk3S0TfDgHaUe1EqqUY=
  template:
    metadata:
      name: cloudflared
      namespace: default
