services:
  tailscale-actual:
    image: tailscale/tailscale:v1.84
    container_name: tailscale-actual
    hostname: actual
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}?ephemeral=false
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/actual.json
    volumes:
      - ${VOLUMES_DIR}/actual/tailscale:/config
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    labels:
      glance.parent: actual
      glance.name: Tailscale

  actual:
    image: ghcr.io/actualbudget/actual:latest
    container_name: actual
    volumes:
      - ${VOLUMES_DIR}/actual/data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    network_mode: service:tailscale-actual
    restart: unless-stopped
    labels:
      glance.id: actual
      glance.name: Actual Budget
      glance.icon: sh:actual-budget
      glance.url: https://actual.owl-augmented.ts.net/

volumes:
  tailscale:
