apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-regular-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: radarr-regular-config
