apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-anime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr-anime
  template:
    metadata:
      labels:
        app: sonarr-anime
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: sonarr-anime
          image: ghcr.io/linuxserver/sonarr:4.0.19
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
              subPath: anime/tv
            # - name: downloads
            #   mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-anime-config
        - name: tv
          persistentVolumeClaim:
            claimName: media
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
