apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-anime-config
  labels:
    name: sonarr-anime-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/sonarr-anime/config"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
