apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.internal.chaldea.dev
  issuerRef:
    name: zerossl-cloudflare-dns01
    kind: ClusterIssuer
