apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  labels:
    name: media
spec:
  capacity:
    storage: 3600Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tank/media"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
