---
- name: Check if ZFS pool exists
  command: zpool list {{ zfs_pool }}
  register: zpool_check
  ignore_errors: true

- name: Check if ZFS pool is available for import
  command: zpool import -f {{ zfs_pool }}
  register: zpool_import
  ignore_errors: true
  when: zpool_check.rc != 0

- name: Create ZFS pool if it does not exist and cannot be imported
  command: "zpool create {{ zfs_pool }} {{ zfs_pool_devices | join(' ') }}"
  when: zpool_check.rc != 0 and zpool_import.rc != 0

- name: Ensure ZFS dataset for each share is present
  community.general.zfs:
    name: "{{ zfs_pool }}/{{ item }}"
    state: present
    extra_zfs_properties:
      mountpoint: "/{{ zfs_pool }}/{{ item }}"
  loop: "{{ zfs_datasets }}"
