services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.6
    container_name: jellyfin
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      JELLYFIN_PublishedServerUrl: https://jellyfin.ryanmalonzo.com
    volumes:
      - ${VOLUMES_DIR}/jellyfin/config:/config
      - /mnt/hdd1/tvshows:/data/tvshows
      - /mnt/hdd1/movies:/data/movies
    devices:
      - /dev/dri:/dev/dri
    networks:
      - jellyfin
      - proxy
    restart: unless-stopped
    labels:
      # traefik
      traefik.enable: true
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.ryanmalonzo.com`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls.certresolver: cloudflare
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      # glance
      glance.name: Jellyfin
      glance.icon: sh:jellyfin
      glance.url: https://jellyfin.ryanmalonzo.com/

networks:
  jellyfin:
    external: true
  proxy:
    external: true
