apiVersion: v1
kind: PersistentVolume
metadata:
  name: papra-config
  labels:
    name: papra-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/papra/app-data"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: papra-documents
  labels:
    name: papra-documents
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tank/documents"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
