apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: papra-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-documents
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: papra-documents
