---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: papra
  namespace: default
spec:
  encryptedData:
    auth-secret: AgC2x4kmcj/MsRChKfKmCEv+YfgJAw7ziIpjoTzgeY33bBMPvpoGTrTrDkeMHLJg9WqOddGCC1tZmmKiZ1XYLmAXRcnRrPYsseLDeBhrGVZPVdUW08qkI8/rv/1y9gODHMo2R910FtKYYNQC51T76YhqIGlScZjXg+wtMcAd7Zhvl1FpNL9U9qmdl1XccPqN7yHFH71z7MwJmmC+NUcX50hlvUXxR+MzErOLAtSMUuajNMBwvKNWS3DoUgJwcsl4vDIiUJgLMrJs+sfQZt6cUfCewrNzvCDhnNhHx3mSKFVk7u8ug8ao7/MKOUPCaCdkKrdplZ4xP8beS4S2XUyEQDZujjN+4lnB6ax5BBxjLALHcl6xq+jLKvV3BoiBkCib8vyao3LnhZjsD61YYPvgfCWbCt9OPVX/CekjEOC6USVsNHSHGjGQOkH2kz2rnB77CmGCUN3hf7uI8MXOPJXeczfduqA0LV/NP5fiwyy3qv07dBJfxmIMSvHdXEWu1GresIA5F8cYb2BaUk6lC7+zJYpnIOUVrpqT7KHqR/979zu4QiFZBbV6kwsyikWP5WGdFZEymoO15dA/ZiM6ZLf/ziPj2cWox3mjyumuh/XtFBuMsxhFDw//abQMq0WUteusESK6pMLWW6gNRErIybthNJzvn5Ji7Xt5j01GV6ZudInR1u7PuwM4OvWR234fO2ge1gycHSwfEEdIHGFvfeCc83+IfE6dyX+cuRJuA7h31XrUzOyXq1vEWLu8oXvDxZWbwM768O4QXjZ3X11dponGXb1XeoOImA9WTL8G/ST/BJxwDvFQzZcsLj9Wvh/PMaQX6qQ=
  template:
    metadata:
      name: papra
      namespace: default
