apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-config
  labels:
    name: technitium-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/technitium/config"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-logs
  labels:
    name: technitium-logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/technitium/logs"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
