apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: technitium-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: technitium-logs
