name: vaultwarden

services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.34.3
    container_name: vaultwarden
    volumes:
      - vaultwarden:/data
    environment:
      DOMAIN: https://vaultwarden.ryanmalonzo.com
    ports:
      - 8000:80
    restart: unless-stopped

volumes:
  vaultwarden:
