name: vaultwarden

services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.34.3
    container_name: vaultwarden
    volumes:
      - vaultwarden:/data
    environment:
      DOMAIN: https://vaultwarden.ryanmalonzo.com
    ports:
      - 8000:80
    labels:
      pangolin.proxy-resources.vaultwarden.name: Vaultwarden
      pangolin.proxy-resources.vaultwarden.protocol: http
      pangolin.proxy-resources.vaultwarden.full-domain: vaultwarden.ryanmalonzo.com
      pangolin.proxy-resources.vaultwarden.auth.sso-enabled: true
      pangolin.proxy-resources.vaultwarden.targets[0].hostname: 192.168.1.253
      pangolin.proxy-resources.vaultwarden.targets[0].port: 8000
      pangolin.proxy-resources.vaultwarden.targets[0].method: http
      pangolin.proxy-resources.vaultwarden.rules[0].match: path
      pangolin.proxy-resources.vaultwarden.rules[0].value: /api/*
      pangolin.proxy-resources.vaultwarden.rules[0].action: allow
      pangolin.proxy-resources.vaultwarden.rules[1].match: path
      pangolin.proxy-resources.vaultwarden.rules[1].value: /identity/*
      pangolin.proxy-resources.vaultwarden.rules[1].action: allow
      pangolin.proxy-resources.vaultwarden.rules[2].match: path
      pangolin.proxy-resources.vaultwarden.rules[2].value: /wl/*
      pangolin.proxy-resources.vaultwarden.rules[2].action: allow
      pangolin.proxy-resources.vaultwarden.rules[3].match: path
      pangolin.proxy-resources.vaultwarden.rules[3].value: /admin/*
      pangolin.proxy-resources.vaultwarden.rules[3].action: deny
      pangolin.proxy-resources.vaultwarden.rules[4].match: path
      pangolin.proxy-resources.vaultwarden.rules[4].value: /alive
      pangolin.proxy-resources.vaultwarden.rules[4].action: allow
    restart: unless-stopped

volumes:
  vaultwarden:
